=== mtaronji/Nova/config/pipeline.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Nova Pipeline Schema",
    "type": "object",
    "required": ["shaderStages", "inputAssembly","rasterizer","multisampling","colorBlend","renderpasskey"],
    "properties": { 
        "shaderStages": {
            "type": "array",
            "items": {
                "type": "object",
                "required": ["stage", "path"],
                "properties": {
                    "stage": {
                        "type": "string",
                        
                        "enum": ["vertex", "fragment", "geometry", "tessellationControl", "tessellationEvaluation", "compute"]
                    },
                    "path": { "type": "string" }
                 }
            }
        },
        "renderpasskey":{
            "type":"string"
        },
        "vertextype":{
            "type":"string",
            "enum":["pc","pn","pnt","pt","pntc"]
        },
        "inputAssembly": {
            "type": "object",
            "required": ["topology","primitiveRestartEnable"],
            "properties": {
                
                "topology": {
                "type": "string",
                "enum": ["point_list", "line_list", "line_strip", "triangle_list", "triangle_strip", "triangle_fan"]
                },
                "primitiveRestartEnable": { "type": "boolean" }
            }
        },
  
        "viewport": {
            "type": "object",
            "properties": {
                "x": { "type": "number" },
                "y": { "type": "number" },
                "width": { "type": "number" },
                "height": { "type": "number" },
                "minDepth": { "type": "number" },
                "maxDepth": { "type": "number" }
            }
        },
  
        "scissor": {
            "type": "object",
                "properties": {
                    "offsetX": { "type": "integer" },
                    "offsetY": { "type": "integer" },
                    "extentWidth": { "type": "integer" },
                    "extentHeight": { "type": "integer" }
                }
        },
  
        "rasterizer": {
            "type": "object",
            "required": ["depthClampEnable","rasterizerDiscardEnable","polygonMode","cullMode","frontFace","depthBiasEnable","lineWidth"],
            "properties": {
                "depthClampEnable": { "type": "boolean" },
                "rasterizerDiscardEnable": { "type": "boolean" },
                "polygonMode": {
                    "type": "string",
                    "enum": ["fill", "line", "point"]
                },
                "lineWidth":{"type":"number"},
                "cullMode": {
                    "type": "string",
                    "enum": ["none", "front", "back", "front_and_back"]
                },
                "frontFace": {
                    "type": "string",
                    "enum": ["clockwise", "counter_clockwise"]
                },
                "depthBiasEnable": { "type": "boolean" }
            }
        },
  
        "multisampling": {
            "type": "object",
            "properties": {
                "rasterizationSamples": { 
                    "type": "integer", 
                    "enum": [1,2,4,8,16,32,64]
                },
                "sampleShadingEnable": { "type": "boolean" },
                "minSampleShading": { "type": "number" }
            }
        },
  
        "depthStencil": {
            "type": "object",
            "properties": {
                "depthTestEnable": { "type": "boolean" },
                "depthWriteEnable": { "type": "boolean" },
                "depthCompareOp": {
                    "type": "string",
                    "enum": ["never", "less", "equal", "less_or_equal", "greater", "not_equal", "greater_or_equal", "always"]
                },
                "stencilTestEnable": { "type": "boolean" }
            }
        },
  
        "colorBlend": {
            "type": "object",
            "required": ["blendConstants"],
            "properties": {
                "logicOpEnable": { "type": "boolean" },
                "logicOp":{
                    "type":"string",
                    "enum":[
                        "VK_LOGIC_OP_CLEAR", 
                        "VK_LOGIC_OP_AND",
                        "VK_LOGIC_OP_AND_REVERSE",
                        "VK_LOGIC_OP_COPY",
                        "VK_LOGIC_OP_AND_INVERTED",
                        "VK_LOGIC_OP_NO_OP",
                        "VK_LOGIC_OP_XOR",
                        "VK_LOGIC_OP_OR",
                        "VK_LOGIC_OP_NOR",
                        "VK_LOGIC_OP_EQUIVALENT",
                        "VK_LOGIC_OP_INVERT",
                        "VK_LOGIC_OP_OR_REVERSE",
                        "VK_LOGIC_OP_COPY_INVERTED",
                        "VK_LOGIC_OP_OR_INVERTED",
                        "VK_LOGIC_OP_NAND",
                        "VK_LOGIC_OP_SET"
                    ]
                },
                "blendConstants": {
                    "type": "array",
                    "items": {
                      "type": "number"
                    },
                    "minItems": 4,
                    "maxItems": 4,
                    "description": "RGBA blend constants, required for constant blend factors."
                },
                "attachments": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "required": ["blendEnable", "colorWriteMask"],
                        "properties": {
                            "blendEnable": { "type": "boolean" },
                            "srcColorBlendFactor": {
                                 "type": "string",
                                 "enum" : [
                                    "VK_BLEND_FACTOR_ZERO","VK_BLEND_FACTOR_ONE","VK_BLEND_FACTOR_SRC_COLOR",	
                                    "VK_BLEND_FACTOR_ONE_MINUS_SRC_COLOR","VK_BLEND_FACTOR_DST_COLOR",	
                                    "VK_BLEND_FACTOR_ONE_MINUS_DST_COLOR","VK_BLEND_FACTOR_SRC_ALPHA",	
                                    "VK_BLEND_FACTOR_ONE_MINUS_SRC_ALPHA","VK_BLEND_FACTOR_DST_ALPHA",
                                    "VK_BLEND_FACTOR_ONE_MINUS_DST_ALPHA","VK_BLEND_FACTOR_CONSTANT_COLOR",
                                    "VK_BLEND_FACTOR_ONE_MINUS_CONSTANT_COLOR","VK_BLEND_FACTOR_CONSTANT_ALPHA",
                                    "VK_BLEND_FACTOR_ONE_MINUS_CONSTANT_ALPHA","VK_BLEND_FACTOR_SRC_ALPHA_SATURATE",	
                                    "VK_BLEND_FACTOR_SRC1_COLOR","VK_BLEND_FACTOR_ONE_MINUS_SRC1_COLOR",
                                    "VK_BLEND_FACTOR_SRC1_ALPHA","VK_BLEND_FACTOR_ONE_MINUS_SRC1_ALPHA"
                                 ]
                            },
                            "dstColorBlendFactor": {
                                 "type": "string",
                                 "enum" : [
                                    "VK_BLEND_FACTOR_ZERO","VK_BLEND_FACTOR_ONE","VK_BLEND_FACTOR_SRC_COLOR",	
                                    "VK_BLEND_FACTOR_ONE_MINUS_SRC_COLOR","VK_BLEND_FACTOR_DST_COLOR",	
                                    "VK_BLEND_FACTOR_ONE_MINUS_DST_COLOR","VK_BLEND_FACTOR_SRC_ALPHA",	
                                    "VK_BLEND_FACTOR_ONE_MINUS_SRC_ALPHA","VK_BLEND_FACTOR_DST_ALPHA",
                                    "VK_BLEND_FACTOR_ONE_MINUS_DST_ALPHA","VK_BLEND_FACTOR_CONSTANT_COLOR",
                                    "VK_BLEND_FACTOR_ONE_MINUS_CONSTANT_COLOR","VK_BLEND_FACTOR_CONSTANT_ALPHA",
                                    "VK_BLEND_FACTOR_ONE_MINUS_CONSTANT_ALPHA","VK_BLEND_FACTOR_SRC_ALPHA_SATURATE",	
                                    "VK_BLEND_FACTOR_SRC1_COLOR","VK_BLEND_FACTOR_ONE_MINUS_SRC1_COLOR",
                                    "VK_BLEND_FACTOR_SRC1_ALPHA","VK_BLEND_FACTOR_ONE_MINUS_SRC1_ALPHA"
                                 ]
                            },
                            "colorBlendOp": { 
                                "type": "string",
                                "enum":[
                                    "VK_BLEND_OP_ADD",	
                                    "VK_BLEND_OP_SUBTRACT",
                                    "VK_BLEND_OP_REVERSE_SUBTRACT",
                                    "VK_BLEND_OP_MIN",
                                    "VK_BLEND_OP_MAX"
                                ]
                            },
                            "srcAlphaBlendFactor": { 
                                "type": "string",
                                "enum" : [
                                    "VK_BLEND_FACTOR_ZERO","VK_BLEND_FACTOR_ONE","VK_BLEND_FACTOR_SRC_COLOR",	
                                    "VK_BLEND_FACTOR_ONE_MINUS_SRC_COLOR","VK_BLEND_FACTOR_DST_COLOR",	
                                    "VK_BLEND_FACTOR_ONE_MINUS_DST_COLOR","VK_BLEND_FACTOR_SRC_ALPHA",	
                                    "VK_BLEND_FACTOR_ONE_MINUS_SRC_ALPHA","VK_BLEND_FACTOR_DST_ALPHA",
                                    "VK_BLEND_FACTOR_ONE_MINUS_DST_ALPHA","VK_BLEND_FACTOR_CONSTANT_COLOR",
                                    "VK_BLEND_FACTOR_ONE_MINUS_CONSTANT_COLOR","VK_BLEND_FACTOR_CONSTANT_ALPHA",
                                    "VK_BLEND_FACTOR_ONE_MINUS_CONSTANT_ALPHA","VK_BLEND_FACTOR_SRC_ALPHA_SATURATE",	
                                    "VK_BLEND_FACTOR_SRC1_COLOR","VK_BLEND_FACTOR_ONE_MINUS_SRC1_COLOR",
                                    "VK_BLEND_FACTOR_SRC1_ALPHA","VK_BLEND_FACTOR_ONE_MINUS_SRC1_ALPHA"
                                 ]
                            },
                            "dstAlphaBlendFactor": { 
                                "type": "string",
                                "enum" : [
                                    "VK_BLEND_FACTOR_ZERO","VK_BLEND_FACTOR_ONE","VK_BLEND_FACTOR_SRC_COLOR",	
                                    "VK_BLEND_FACTOR_ONE_MINUS_SRC_COLOR","VK_BLEND_FACTOR_DST_COLOR",	
                                    "VK_BLEND_FACTOR_ONE_MINUS_DST_COLOR","VK_BLEND_FACTOR_SRC_ALPHA",	
                                    "VK_BLEND_FACTOR_ONE_MINUS_SRC_ALPHA","VK_BLEND_FACTOR_DST_ALPHA",
                                    "VK_BLEND_FACTOR_ONE_MINUS_DST_ALPHA","VK_BLEND_FACTOR_CONSTANT_COLOR",
                                    "VK_BLEND_FACTOR_ONE_MINUS_CONSTANT_COLOR","VK_BLEND_FACTOR_CONSTANT_ALPHA",
                                    "VK_BLEND_FACTOR_ONE_MINUS_CONSTANT_ALPHA","VK_BLEND_FACTOR_SRC_ALPHA_SATURATE",	
                                    "VK_BLEND_FACTOR_SRC1_COLOR","VK_BLEND_FACTOR_ONE_MINUS_SRC1_COLOR",
                                    "VK_BLEND_FACTOR_SRC1_ALPHA","VK_BLEND_FACTOR_ONE_MINUS_SRC1_ALPHA"
                                 ]
                            },
                            "alphaBlendOp": { 
                                "type": "string",
                                "enum":[
                                    "VK_BLEND_OP_ADD",	
                                    "VK_BLEND_OP_SUBTRACT",
                                    "VK_BLEND_OP_REVERSE_SUBTRACT",
                                    "VK_BLEND_OP_MIN",
                                    "VK_BLEND_OP_MAX"
                                ]
                            },
                            "colorWriteMask": {
                                "type": "array",
                                "items": {
                                    "type": "string",
                                    "enum": ["r", "g", "b", "a"]
                                }
                            }
                        }
                    }
                }
            }
        },
  
        "dynamicStates": {
            "type": "array",
            "items": {
                "type": "string",
                "enum": [
                    "viewport", "scissor", "lineWidth", "depthBias", "blendConstants",
                    "depthBounds", "stencilCompareMask", "stencilWriteMask", "stencilReference"
                ]
            }
        },

      "pushConstants": {
        "type": "array",
        "items": {
          "type": "object",
          "required": [ "stage", "offset", "name" ],
          "properties": {
            "stage": {
              "type": "array",
              "items": {
                "type": "string",
                "enum": [
                  "vertex",
                  "fragment",
                  "geometry",
                  "compute",
                  "tessellationControl",
                  "tessellationEvaluation",
                  "allGraphics",
                  "all",
                  "raygen",
                  "anyHit",
                  "closestHit",
                  "miss",
                  "intersection",
                  "callable",
                  "task",
                  "mesh"
                ]
              }
            },
            "offset": { "type": "integer" },
            "name": {
              "type": "string",
              "enum": [ "frameinfo" ],
              "description": "name of the actual datatype"
            }

          }
        }
      },
      "descriptorFile": {
        "type": "string",
        "description": "name of the file we define our descriptor Sets in"
      }
    }
}

=== mtaronji/Nova/pipelines/msaa4.json
{
  "$schema": "../config/pipeline.schema.json",
    "shaderStages": [
        {"stage": "vertex","path": "shaders/identity.vert.spv"},
        {"stage": "fragment","path": "shaders/identity.frag.spv"}
    ],
    "inputAssembly": {
        "topology": "triangle_list",
        "primitiveRestartEnable": false
    },
    "rasterizer": {
      "depthClampEnable": false,
      "rasterizerDiscardEnable": false,
      "polygonMode": "fill",
      "cullMode": "none",
      "depthBiasEnable": false,
      "frontFace": "counter_clockwise",
      "lineWidth": 1.0
    },
    "renderpasskey": "msaa4.json",
    "vertextype": "pc",
    "multisampling": {
        "sampleShadingEnable": true,
        "rasterizationSamples":4,
        "minSampleShading": 0.5
    },
    "depthStencil": {
        "depthCompareOp": "less",
        "depthTestEnable": true,
        "depthWriteEnable": true,
        "stencilTestEnable": false
    },
    "colorBlend": {
        "logicOp": "VK_LOGIC_OP_COPY",
        "logicOpEnable": false,
        "blendConstants": [0.0, 0.0, 0.0, 0.0],
        
        "attachments": [
            {
                "blendEnable": false,
                "colorWriteMask": ["r","g","b","a"]
                
            }
        ]
    },
    "dynamicStates": [
        "viewport","scissor"
    ],

  "pushConstants": [
    {
      "name": "frameinfo",
      "offset": 0,
      "stage": [ "vertex", "fragment" ]
    }
  ],
  "descriptorFile": "default.json" 
}
